outputs = "All"
position = "Top"

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = 'alacritty -e bash -c "yay; echo Done - Press enter to exit; read" &'

[workspaces]
visibility_mode = "All"
enable_workspace_filling = true

[window_title]
mode = "Title"
truncate_title_after_length = 75

[system_info]
indicators = [ "Cpu", "Memory", "Temperature", "DownloadSpeed", "UploadSpeed" ]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80

[tray]
